version: '3'
services:
  node:
    container_name: node-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./react:/react
    - ./vue:/vue
    ports:
      - "3000:3000"
      - "8080:8080"
    tty: true
    stdin_open: true
    # Hot Module Replacement (HMR) is enable for virtual box.
    environment:
      - CHOKIDAR_USEPOLLING=true